package app.iui.flow;

/**
 * @author Igor Usenko
 *         Date: 27.11.2010
 */
public enum ModelType {
    CHOOSE_MAIN_TASK,
    CHOOSE_FEEDERS,
    CHOOSE_FEEDERS_TASK,
    CHANGE_SETTINGS,
    EXTERNAL_TOOLS_SETTINGS,
    EXTERNAL_POSTPROCESSOR_SETTINGS,
    MESSAGE,
    SELECT_WORKSPACE,
    CHOOSE_FETCH_MODE,
    UPDATE_FEEDER,
    UPDATE_FEEDERS,
    LOADING_WORKSPACE,
    UPDATED_FILES,
    FORCED_UPDATE_PERIOD,
    UPDATE_CONTEXT,
    CHOOSE_WORKSPACE_TASK,
    EDIT_WORKSPACE_NAME,
    DELETE_WORKSPACE_CONFIRMATION,
    DELETE_SIMPLE_FEEDER_CONFIRMATION,
    SIMPLE_FEEDER,
    CHOOSE_FEEDER_DEBUG_ACTION,
    GOOGLE_READER_CHOOSE_TASK,
    GOOGLE_READER_MANAGE_PROFILES,
    ERROR,
    NOT_IMPLEMENTED
}
